### ISSUE TITLE
convert package seems to have no equiv of url safe base 64

### ISSUE THREAD

**Issue by Andersmholmgren** [dart-lang/crypto#32]
I converted the `dart_jwt` package to the latest `crypto` (pre 1.0) version and followed the deprecation advice to use the `convert` package for base64.

Unfortunately all my tests started failing as they encoding was not the same as you get with the url safe version of the old base64.

I need the equivalent of 

```
const Base64Codec(urlSafe: true).decode(...);
```

to exist in the convert package but can't find it. What am I missing?

**Comment by nex3** [comment]
I believe the deprecation message for `base64` suggests that you use `dart:convert`, not the `convert` package. Either way, this is a feature request that should be filed against the repo that now contains the base64 implementation.

I believe @lrhn didn't want to include URL-safe encoding in the core library because it was extra complexity that could easily be layered on top by the caller.

**Comment by Andersmholmgren** [comment]
Sorry I meant `dart:convert`. I didn't actually realise there was a `convert` package. 

Either way that functionality was deprecated and removed from this package without being included in what we are told to use instead. 

This means of course that all packages that depend on url safe base64 either need to implement it themselves or are forever stuck on the older version of crypto. 

Not a great choice for us in the long run

**Comment by Andersmholmgren** [comment]
https://github.com/dart-lang/sdk/issues/26186
